### ISSUE TITLE
npm ERR! Failed at the webpack-handbook@0.0.3 serve-gitbook script 'gitbook serve ./content ./gh-pages'.

### ISSUE THREAD

**Issue by jiushiliu** [zhaoda/webpack-handbook#16]
npm ERR! Failed at the webpack-handbook@0.0.3 serve-gitbook script 'gitbook serve ./content ./gh-pages'.
npm ERR! This is most likely a problem with the webpack-handbook package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gitbook serve ./content ./gh-pages

**Comment by zhaoda** [comment]
`npm install` 成功了么

**Comment by meishadevs** [comment]
使用淘宝镜像 cnpm
