### ISSUE TITLE
问个关于webpack的问题

### ISSUE THREAD

**Issue by zeyongTsai** [zhaoda/webpack-handbook#2]
跟着您翻译的文章走，如果是在webpack.config.js配置文件中加入了css相关的loader，并且在入口文件中引入了css模块，则会直接报错Module not found...配置文件都很简单，不加css相关的都不会报错，请问您知道这个问题的原因吗？不使用配置文件方式的话倒是可行的；我看了一下css-loader，里面的module非常多，文件目录也很深，所以是不是因为win7对文件路径256字符限制导致模块不能正常加载呢？英文不好，只好来问您了。 : (

**Comment by zeyongTsai** [comment]
extensions少了空值！！！ - -

**Comment by zhaoda** [comment]
我的文章里也少了空值么？

**Comment by zeyongTsai** [comment]
文章里面没有写，我在别处看到可以写，想在require的时候不写扩展名，结果……

從我的 iPhone 傳送

**Comment by zhaoda** [comment]
恩，第一个应该是空值，其实 webpack 应该自动将空值默认是第一个，就不用填写了，因为大部分情况都会把空值设置为第一个。

``` js
        resolve: {
            root: [srcDir],
            alias: sourceMap,
            extensions: ['', '.js', 'jsx', '.css', '.scss', 'less', '.tpl', '.png', '.jpg']
        },
```
