### ISSUE TITLE
执行代码报错，望解答

### ISSUE THREAD

**Issue by Miogaror** [zhaoda/webpack-handbook#21]
`{test: /\.css$/, loader: 'style!css'}`

执行`webpack`命令时报错

```
ERROR in ./entry.js
Module not found: Error: Can't resolve 'style' in '/home/lethe/work/xinhua-backstage'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'style-loader' instead of 'style'.
 @ ./entry.js 1:0-22

ERROR in ./entry.js
Module not found: Error: Can't resolve 'style' in '/home/lethe/work/xinhua-backstage'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'style-loader' instead of 'style'.
 @ ./entry.js 2:0-22
```
我从网上查了，将`{test: /\.css$/, loader: 'style!css'}`改为` { test: /\.css$/, loader: "style-loader!css-loader" }`可以正常运行，但是不知道原因，麻烦帮忙解答下，万分感谢@zhaoda

**Comment by zhaoda** [comment]
错误信息里不是明确写了么？

ERROR in ./entry.js
Module not found: Error: Can't resolve 'style' in
'/home/lethe/work/xinhua-backstage'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix
when using loaders.
                 You need to specify 'style-loader' instead of 'style'.
 @ ./entry.js 1:0-22

应该是你的版本比我当时用的版本高了，所以这个语法变更了，你改成 '-loader' 可以用了就好。

**Comment by allenGKC** [comment]
{test: /\.css$/, loader: 'style!css'}改成{test: /\.css$/, loader: 'style-loader!css-loader'}

**Comment by RaiyenXiao** [comment]
我也遇到同样的问题 配置文件改成{test: /.css$/, loader: 'style-loader!css-loader'} 可以执行出来，但是只能webpack entry.js bundle.js
而如果像文档中是webpack entry.js bundle.js --module-bind “css=style!css” 会报错
>webpack entry.js bundle.js --module-bind "css=style!css"
Hash: 8c739f82d647f409e4f6
Version: webpack 2.2.1
Time: 235ms
    Asset     Size  Chunks             Chunk Names
bundle.js  38.3 kB       0  [emitted]  main
   [0] ./entry.js 176 bytes {0} [built]
   [1] ./bundle.js 35.1 kB {0} [built]
   [2] ./module.js 88 bytes {0} [built]
   [3] multi ./entry.js ./entry.js ./bundle.js 52 bytes {0} [built]

ERROR in ./entry.js
Module not found: Error: Can't resolve 'style' in 'E:\K\vue'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'style-loader' instead of 'style'.
 @ ./entry.js 5:0-22
 @ multi ./entry.js ./entry.js ./bundle.js
不太明白为什么，而且浏览器虽然样式加载出来了，也会报错：如下
Uncaught Error: Cannot find module "./style.css"
    at webpackMissingModule (bundle.js:162)
    at Object.installedModules (bundle.js:162)
    at __webpack_require__ (bundle.js:105)
    at Object.<anonymous> (bundle.js:1367)
    at __webpack_require__ (bundle.js:105)
    at bundle.js:151
    at Object.module.exports (bundle.js:154)
    at __webpack_require__ (bundle.js:20)
    at Object.<anonymous> (bundle.js:1738)
    at __webpack_require__ (bundle.js:20)

**Comment by pakoneko** [comment]
大大您好 我想问一下 webpack在命令行里使用是不是一定要全局安装的？
我在apps文件夹下安装 在命令行尝试运行打包的命令 返回的是 command not found

**Comment by zhaoda** [comment]
@showermj 是的
```js
npm install webpack -g
```
