### ISSUE TITLE
下载的电子版字体明显不一致？

### ISSUE THREAD

**Issue by byr-gdp** [zhaoda/webpack-handbook#4]
![image](https://cloud.githubusercontent.com/assets/9307206/11921598/f74a9820-a7c6-11e5-807d-863493600330.png)

是由于系统自身原因还是普遍的呢？

**Comment by zhaoda** [comment]
普遍

**Comment by zhaoda** [comment]
用epub或mobi版本吧，pdf确实效果不好

**Comment by byr-gdp** [comment]
@zhaoda thx
