### ISSUE TITLE
不如合作将官方文档翻译成中文？

### ISSUE THREAD

**Issue by e-cloud** [zhaoda/webpack-handbook#6]

**Comment by zhaoda** [comment]
我这个书就是在官方文档基础上翻译整理的，只是还没完，只是基础章节。官方文档的结构和内容有些重复和混乱，官网左侧目录的体系不是循序渐进的。

**Comment by e-cloud** [comment]
明白，你是打算做成一条龙教程。在我看来，官方文档毕竟是相对最齐全。左手一个指南，右手一个官方参考，学习起来可能会更高效

**Comment by cos800** [comment]
支持将官方文档翻译成中文
